### ISSUE TITLE
Crashing on SMBIOS 3.1

### ISSUE THREAD

**Issue by DexterWoo** [iAJTin/iSMBIOS#1]
got a system that's on SMBIOS 3.1, the program crashed when trying to get the property for Type0.

at iTin.Core.Helpers.SentinelHelper.IsTrue(Boolean expression, String message)
   at iTin.Core.Helpers.SentinelHelper.IsTrue(Boolean expression)
   at iTin.Core.Int32Extensions.GetByte(Int32 value, Byte onebyte)
   at iTin.Core.Int32Extensions.GetByte(Int32 value, Bytes onebyte)
   at iTin.Core.Hardware.Specification.Smbios.SmbiosType000.get_ExtendedBiosRomSizeUnits() in C:\iSMBIOS\src\iTin.Core.Hardware\Specification\SMBIOS\Structures\SmbiosType000 [BIOS Information].cs:line 347
   at iTin.Core.Hardware.Specification.Smbios.SmbiosType000.Parse(Hashtable properties) in C:\iSMBIOS\src\iTin.Core.Hardware\Specification\SMBIOS\Structures\SmbiosType000 [BIOS Information].cs:line 550
   at iTin.Core.Hardware.Specification.Smbios.SmbiosBaseType.get_Properties() in C:\iSMBIOS\src\iTin.Core.Hardware\Specification\SMBIOS\Structures\SmbiosBaseType.cs:line 84
   at iTin.Core.Hardware.Specification.Dmi.DmiClass.get_Properties() in C:\iSMBIOS\src\iTin.Core.Hardware\Specification\DMI\DmiClass.cs:line 48

I checked the function, it seems the logic is throwing exception intentionally?

**Comment by DexterWoo** [comment]
byte unit = value.GetByte(Bytes.Byte03);  this code will always throw exception since there's the is true will always work whenever this is called.

**Comment by DexterWoo** [comment]
came with a PR for you to fix~

**Comment by iAJTin** [comment]
Thanks,
